# Generated by Django 4.0.2 on 2022-09-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default='', max_length=10)),
                ('selling_price', models.FloatField(default='', max_length=50)),
                ('kilometer_driven', models.FloatField(default='', max_length=50)),
                ('fuel_type', models.IntegerField(default='', max_length=10)),
                ('seller_type', models.IntegerField(default='', max_length=10)),
                ('transmission', models.IntegerField(default='', max_length=10)),
                ('owner', models.IntegerField(default='', max_length=10)),
            ],
        ),
    ]
