# Generated by Django 4.0.2 on 2022-09-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PricePredictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='fuel_type',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='kilometer_driven',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='owner',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='seller_type',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='selling_price',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='transmission',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.IntegerField(default=''),
        ),
    ]
